import { SdkError } from '../../../errors';
import { ResponseBase } from '../response-base';
export interface SearchHit {
    id: string;
    score: number;
    metadata: Record<string, string | number | boolean | Array<string>>;
}
/**
 * Parent response type for a VectorSearch request.  The
 * response object is resolved to a type-safe object of one of
 * the following subtypes:
 *
 * - {Success}
 * - {Error}
 *
 * `instanceof` type guards can be used to operate on the appropriate subtype.
 * @example
 * For example:
 * ```
 * if (response instanceof VectorSearch.Error) {
 *   // Handle error as appropriate.  The compiler will smart-cast `response` to type
 *   // `VectorSearch.Error` in this block, so you will have access to the properties
 *   // of the Error class; e.g. `response.errorCode()`.
 * }
 * ```
 */
export declare abstract class Response extends ResponseBase {
    hits(): Array<SearchHit> | undefined;
}
declare class _Success extends Response {
}
declare const Success_base: {
    new (...args: any[]): {
        readonly is_success: boolean;
    };
} & typeof _Success;
/**
 * Indicates a Successful VectorSearch request.
 */
export declare class Success extends Success_base {
    private readonly _hits;
    constructor(hits: Array<SearchHit>);
    hits(): Array<SearchHit>;
}
declare class _Error extends Response {
    protected _innerException: SdkError;
    constructor(_innerException: SdkError);
}
declare const Error_base: {
    new (...args: any[]): {
        _innerException: SdkError;
        message(): string;
        innerException(): SdkError;
        errorCode(): import("../../../errors").MomentoErrorCode;
        toString(): string;
    };
} & typeof _Error;
/**
 * Indicates that an error occurred during the VectorSearch request.
 *
 * This response object includes the following fields that you can use to determine
 * how you would like to handle the error:
 *
 * - `errorCode()` - a unique Momento error code indicating the type of error that occurred.
 * - `message()` - a human-readable description of the error
 * - `innerException()` - the original error that caused the failure; can be re-thrown.
 */
export declare class Error extends Error_base {
}
export {};
